name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - ipycanvas
  - jinja2
  - matplotlib
  - numpy<2
  - pandas
  - python=3.11
  - simpy
  - xeus-python
  - plotly
  - jupyterlab-geojson
  - piplite
